#define N 47
#define INF 10000

int a[N+1][N+1] ={{0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0,	0},
{0,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF,	INF},
{0,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	1,},
{0,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	1,	INF,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	1,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	0,	INF,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0,	INF},
{0,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	1,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	INF,	0}};

int value[N+1];
int f[N+1];
int index[N+1];

int main(){
	int min,p,n,i,j,k;
	
	for(n=1; n <=N; n++){
		value[n] = INF;
	}
	value[1] = 0;
	
	for(i = 1 ; i<=N;i++ ){
		min=INF;
		for(j = 0;j<=N;j++){
			if((value[j]<min) && f[j] == 0){
				min=value[j];
				p=i;
			}
		}
		f[p] = 1;
		for(k=1;k<=N;k++){
			if(value[p]+a[p][k] < value[k]){
				value[k] = value[p]+a[p][k];
				index[k] = p;
			}
		}	
	}
	
	for(i = 1;i <=N ; i++){
		printf("%d : 1->%d", value[i],i);
		printf(" ");
		p = i;
		
		do{
			printf("<-%d", index[p]);
			p=index[p];
		}
		while(index[p]);
		puts("");
	}
	
}
